# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
install findutils

# Install Bash 4
install bash

# Install more recent versions of vim and grep
install vim --override-system-vi

tap homebrew/dupes
install homebrew/dupes/grep

# Install htop
install htop-osx

# Install wget with IRI support
install wget --enable-iri

# Install other useful binaries
install git
install sqlite
install tmux

install ack		# grep for source code
install tree	# recursive directory listing command
install webkit2png	# captures webpage screenshots 

# Remove outdated versions from the cellar
cleanup
